name: Deploy Frontend

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4 

      - name: Configurer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0' 

      - name: Installer les dépendances Angular CLI et du projet
        run: |
          npm install -g @angular/cli 
          npm install

      - name: Compiler application Angular pour la production
        run: ng build --configuration production --base-href=/ --deploy-url=/frontend/
        
      - name: Récupérer le nom du projet Angular (pour le dossier dist)
        id: get_app_name
        run: echo "APP_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV 

      - name: Déployer sur le serveur via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0 
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp 
          local-dir: ./dist/fanilovitrine/browser/ 
          server-dir: ${{ secrets.FTP_REMOTE_PATH }} 
